stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - docker build -t shortenit-ci .

test-job:
  stage: test
  script:
    - echo "Running tests..."
    - sleep 20
    - echo "Let's pretend that all tests succeed..."

deploy-job:
  stage: deploy
  script:
    - docker compose up -d